[project]
name = "cookiecutter-python-template"
version = "0.1.0"
description = "Cookie-cutter template for a basic Python project set-up"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cookiecutter>=2.6.0",
    "isort>=6.0.1",
    "mypy>=1.15.0",
    "ruff>=0.11.10",
]
