[project]
name = {{ cookiecutter.project_name }}

version = "0.1.0"
description = {{ cookiecutter.project_short_description }}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cookiecutter>=2.6.0",
    "isort>=6.0.1",
    "mypy>=1.15.0",
    "ruff>=0.11.10",
]
